export const SET_RUNNING = 'SET_RUNNING'
export const SET_GRID = 'SET_GRID'
export const SIM_GENERATION = 'SIM_GENERATION'
export const CLICK_CELL = 'CLICK_CELL'
export const SET_RANDOM_GRID = 'SET_RANDOM_GRID'